/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Run 'yarn update-api-types' to regenerate.
 */

/**
 * FIPS Code. FIPS codes are either 2-digit state codes, 5-digit county codes, 5-digit CBSA codes, or 1-digit '0' for the entire USA.
 */
export type Fips = string;
/**
 * 2-letter ISO-3166 Country code.
 */
export type Country = string;
/**
 * 2-letter ANSI state code. For CBSA regions, state is omitted.
 */
export type State = string | null;
/**
 * County name
 */
export type County = string | null;
/**
 * 3 digit Health Service Area identification code. For CBSA, state, and country regions hsa is omitted. For more on HSAs see: https://github.com/covid-projections/covid-data-model/blob/main/data/misc/README.md
 */
export type Hsa = string | null;
/**
 * Name of Health Service Area. For CBSA, state, and country regions hsaName is omitted. For more on HSAs see: https://github.com/covid-projections/covid-data-model/blob/main/data/misc/README.md
 */
export type Hsaname = string | null;
/**
 * An enumeration.
 */
export type AggregationLevel =
  | 'country'
  | 'state'
  | 'county'
  | 'cbsa'
  | 'place'
  | 'hsa';
/**
 * Latitude of point within the state or county. Currently a placeholder.
 */
export type Lat = number | null;
/**
 * Location ID as defined here: https://github.com/covidatlas/li/blob/master/docs/reports-v1.md#general-notes
 */
export type Locationid = string;
/**
 * Longitude of point within the state or county. Currently a placeholder.
 */
export type Long = number | null;
/**
 * Total Population in geographic region.
 */
export type Population = number;
/**
 * Total Population of county's corresponding Health Service Area. For CBSA, state, and country regions hsaPopulation is omitted. For more on HSAs see: https://github.com/covid-projections/covid-data-model/blob/main/data/misc/README.md
 */
export type Hsapopulation = number | null;
/**
 * Ratio of people who test positive calculated using a 7-day rolling average.
 */
export type Testpositivityratio = number | null;
/**
 * Method used to determine test positivity ratio.
 */
export type TestPositivityRatioMethod =
  | 'CMSTesting'
  | 'CDCTesting'
  | 'HHSTesting'
  | 'Valorum'
  | 'covid_tracking'
  | 'other';
/**
 * The number of cases per 100k population calculated using a 7-day rolling average.
 */
export type Casedensity = number | null;
/**
 * The number of new cases per 100k population over the last week.
 */
export type Weeklynewcasesper100K = number | null;
/**
 * Ratio of currently hired tracers to estimated tracers needed based on 7-day daily case average.
 */
export type Contacttracercapacityratio = number | null;
/**
 * R_t, or the estimated number of infections arising from a typical case.
 */
export type Infectionrate = number | null;
/**
 * 90th percentile confidence interval upper endpoint of the infection rate.
 */
export type Infectionrateci90 = number | null;
/**
 * Ratio of staffed intensive care unit (ICU) beds that are currently in use.
 */
export type Icucapacityratio = number | null;
/**
 * Ratio of staffed hospital beds that are currently in use by COVID patients. For counties, this is calculated using HSA-level data for the corresponding area.
 */
export type Bedswithcovidpatientsratio = number | null;
/**
 * Number of COVID patients per 100k population admitted in the past week. For counties, this is calculated using HSA-level data for the corresponding area.
 */
export type Weeklycovidadmissionsper100K = number | null;
/**
 * Ratio of population that has initiated vaccination.
 */
export type Vaccinationsinitiatedratio = number | null;
/**
 * Ratio of population that has completed vaccination.
 */
export type Vaccinationscompletedratio = number | null;
/**
 * Ratio of population that are fully vaccinated and have received a booster (or additional) dose.
 */
export type Vaccinationsadditionaldoseratio = number | null;
/**
 * Risk levels for region.
 */
export type Risklevels = RiskLevels;
/**
 * COVID Risk Level.
 *
 * ## Risk Level Definitions
 *  *Low* - On track to contain COVID
 *  *Medium* - Slow disease growth
 *  *High* - At risk of outbreak
 *  *Critical* - Active or imminent outbreak
 *  *Unknown* - Risk unknown
 *  *Extreme* - Severe outbreak
 */
export type RiskLevel = 0 | 1 | 2 | 3 | 4 | 5;
/**
 * CDC community transmission level.
 */
export type CDCTransmissionLevel = 0 | 1 | 2 | 3 | 4;
/**
 * Community level.
 */
export type CommunityLevel = 0 | 1 | 2;
/**
 * Cumulative confirmed or suspected cases.
 */
export type Cases = number | null;
/**
 * Cumulative deaths that are suspected or confirmed to have been caused by COVID-19.
 */
export type Deaths = number | null;
/**
 * Cumulative positive test results to date
 */
export type Positivetests = number | null;
/**
 * Cumulative negative test results to date
 */
export type Negativetests = number | null;
/**
 * Number of Contact Tracers
 */
export type Contacttracers = number | null;
/**
 *
 * Information about acute bed utilization details.
 *
 * Fields:
 *  * capacity - Current staffed acute bed capacity.
 *  * currentUsageTotal - Total number of acute beds currently in use
 *  * currentUsageCovid - Number of acute beds currently in use by COVID patients.
 *  * weeklyCovidAdmissions - Number of COVID patients admitted in the past week.
 *
 */
export type Hospitalbeds = HospitalResourceUtilizationWithAdmissions;
/**
 * Total capacity for resource.
 */
export type Capacity = number | null;
/**
 * Currently used capacity for resource by all patients (COVID + Non-COVID)
 */
export type Currentusagetotal = number | null;
/**
 * Currently used capacity for resource by COVID
 */
export type Currentusagecovid = number | null;
/**
 * Number of COVID patients admitted in the past week.
 */
export type Weeklycovidadmissions = number | null;
/**
 *
 * Information about acute bed utilization details aggregated for the county's corresponding
 * Health Service Area (HSA). For CBSA, state, and country regions these fields are omitted.
 * For more on HSAs see: https://github.com/covid-projections/covid-data-model/blob/main/data/misc/README.md"
 *
 * Fields:
 *  * capacity - Current staffed acute bed capacity.
 *  * currentUsageTotal - Total number of acute beds currently in use
 *  * currentUsageCovid - Number of acute beds currently in use by COVID patients.
 *  * weeklyCovidAdmissions - Number of COVID patients admitted in the past week.
 *
 */
export type Hsahospitalbeds = HospitalResourceUtilizationWithAdmissions;
/**
 *
 * Information about ICU bed utilization details.
 *
 * Fields:
 *  * capacity - Current staffed ICU bed capacity.
 *  * currentUsageTotal - Total number of ICU beds currently in use
 *  * currentUsageCovid - Number of ICU beds currently in use by COVID patients.
 *
 */
export type Icubeds = HospitalResourceUtilization;
/**
 * Total capacity for resource.
 */
export type Capacity1 = number | null;
/**
 * Currently used capacity for resource by all patients (COVID + Non-COVID)
 */
export type Currentusagetotal1 = number | null;
/**
 * Currently used capacity for resource by COVID
 */
export type Currentusagecovid1 = number | null;
/**
 *
 * Information about ICU bed utilization details aggregated for the county's corresponding
 * Health Service Area (HSA). For CBSA, state, and country regions these fields are omitted.
 * For For more on HSAs see: https://github.com/covid-projections/covid-data-model/blob/main/data/misc/README.md"
 *
 * Fields:
 *  * capacity - Current staffed ICU bed capacity.
 *  * currentUsageTotal - Total number of ICU beds currently in use
 *  * currentUsageCovid - Number of ICU beds currently in use by COVID patients.
 *
 */
export type Hsaicubeds = HospitalResourceUtilization;
/**
 *
 * New confirmed or suspected cases.
 *
 *
 * New cases are a processed timeseries of cases - summing new cases may not equal
 * the cumulative case count.
 *
 * Processing steps:
 *  1. If a region does not report cases for a period of time but then begins reporting again,
 *     we will exclude the first day that reporting recommences. This first day likely includes
 *     multiple days worth of cases and can be misleading to the overall series.
 *  2. We remove any days with negative new cases.
 *  3. We apply an outlier detection filter to the timeseries, which removes any data
 *     points that seem improbable given recent numbers. Many times this is due to
 *     backfill of previously unreported cases.
 *
 */
export type Newcases = number | null;
/**
 *
 * New confirmed or suspected COVID-19 deaths.
 *
 * New deaths is an estimate of deaths per day; summing new deaths may not equal the
 * cumulative death count.
 *
 * Processing steps:
 *  1. If a region does not report deaths for a period of time but then begins reporting again,
 *     we will exclude the first day that reporting recommences. This first day likely includes
 *     multiple days worth of deaths and can be misleading to the overall series.
 *  2. We remove any days with negative new deaths.
 *  3. We apply an outlier detection filter to the timeseries, which removes any data
 *     points that seem improbable given recent numbers. Many times this is due to
 *     backfill of previously unreported deaths.
 *
 */
export type Newdeaths = number | null;
/**
 * Number of vaccine doses distributed.
 */
export type Vaccinesdistributed = number | null;
/**
 *
 * Number of vaccinations initiated.
 *
 * This value may vary by type of vaccine, but for Moderna and Pfizer this indicates
 * number of people vaccinated with the first dose.
 *
 */
export type Vaccinationsinitiated = number | null;
/**
 *
 * Number of vaccinations completed.
 *
 * This value may vary by type of vaccine, but for Moderna and Pfizer this indicates
 * number of people vaccinated with both the first and second dose.
 *
 */
export type Vaccinationscompleted = number | null;
/**
 * Number of individuals who are fully vaccinated and have received a booster (or additional) dose.
 */
export type Vaccinationsadditionaldose = number | null;
/**
 * Total number of vaccine doses administered.
 */
export type Vaccinesadministered = number | null;
/**
 * Demographic distributions for administered vaccines.
 */
export type Vaccinesadministereddemographics = DemographicDistributions;
export type Age = {
  [k: string]: any;
} | null;
export type Race = {
  [k: string]: any;
} | null;
export type Ethnicity = {
  [k: string]: any;
} | null;
export type Sex = {
  [k: string]: any;
} | null;
/**
 * Demographic distributions for initiated vaccinations.
 */
export type Vaccinationsinitiateddemographics = DemographicDistributions;
/**
 * Annotations for cases
 */
export type Cases1 = FieldAnnotations;
/**
 * The data source of a field (metric or actual). This enumeration lists the places from which
 * CAN fetches data. The source is tracked on a per field and region timeseries basis.
 */
export type FieldSourceType =
  | 'NYTimes'
  | 'CMSTesting'
  | 'CDCTesting'
  | 'HHSTesting'
  | 'HHSHospital'
  | 'Valorum'
  | 'covid_tracking'
  | 'USAFacts'
  | 'TestAndTrace'
  | 'CANScrapersStateProviders'
  | 'other';
/**
 * URL of a webpage containing the data at the source
 */
export type Url = string | null;
/**
 * A human readable name of the source
 */
export type Name = string | null;
export type Sources = FieldSource[];
/**
 * Date of anomaly
 */
export type Date = string;
/**
 * The type of the annotation.
 *
 * Each enumeration refers to the method used to generate the annotation.
 */
export type TagType =
  | 'cumulative_tail_truncated'
  | 'cumulative_long_tail_truncated'
  | 'zscore_outlier'
  | 'known_issue'
  | 'known_issue_no_date'
  | 'derived'
  | 'drop_future_observation'
  | 'provenance'
  | 'source_url'
  | 'source';
/**
 * Original value on this date detected as anomalous.
 */
export type OriginalObservation = number;
export type Anomalies = AnomalyAnnotation[];
/**
 * Annotations for deaths
 */
export type Deaths1 = FieldAnnotations;
/**
 * Annotations for positiveTests
 */
export type Positivetests1 = FieldAnnotations;
/**
 * Annotations for negativeTests
 */
export type Negativetests1 = FieldAnnotations;
/**
 * Annotations for contactTracers
 */
export type Contacttracers1 = FieldAnnotations;
/**
 * Annotations for hospitalBeds
 */
export type Hospitalbeds1 = FieldAnnotations;
/**
 * Annotations for hsaHospitalBeds
 */
export type Hsahospitalbeds1 = FieldAnnotations;
/**
 * Annotations for icuBeds
 */
export type Icubeds1 = FieldAnnotations;
/**
 * Annotations for hsaIcuBeds
 */
export type Hsaicubeds1 = FieldAnnotations;
/**
 * Annotations for newCases
 */
export type Newcases1 = FieldAnnotations;
/**
 * Annotations for newDeaths
 */
export type Newdeaths1 = FieldAnnotations;
/**
 * Annotations for vaccinesDistributed
 */
export type Vaccinesdistributed1 = FieldAnnotations;
/**
 * Annotations for vaccinationsInitiated
 */
export type Vaccinationsinitiated1 = FieldAnnotations;
/**
 * Annotations for vaccinationsCompleted
 */
export type Vaccinationscompleted1 = FieldAnnotations;
/**
 * Annotations for vaccinationsAdditionalDose
 */
export type Vaccinationsadditionaldose1 = FieldAnnotations;
/**
 * Annotations for vaccinesAdministered
 */
export type Vaccinesadministered1 = FieldAnnotations;
/**
 * Annotations for testPositivityRatio
 */
export type Testpositivityratio1 = FieldAnnotations;
/**
 * Annotations for caseDensity
 */
export type Casedensity1 = FieldAnnotations;
/**
 * Annotations for weeklyNewCasesPer100k
 */
export type Weeklynewcasesper100K1 = FieldAnnotations;
/**
 * Annotations for contactTracerCapacityRatio
 */
export type Contacttracercapacityratio1 = FieldAnnotations;
/**
 * Annotations for infectionRate
 */
export type Infectionrate1 = FieldAnnotations;
/**
 * Annotations for infectionRateCI90
 */
export type Infectionrateci901 = FieldAnnotations;
/**
 * Annotations for icuCapacityRatio
 */
export type Icucapacityratio1 = FieldAnnotations;
/**
 * Annotations for bedsWithCovidPatientsRatio
 */
export type Bedswithcovidpatientsratio1 = FieldAnnotations;
/**
 * Annotations for weeklyCovidAdmissionsPer100k
 */
export type Weeklycovidadmissionsper100K1 = FieldAnnotations;
/**
 * Annotations for vaccinationsInitiatedRatio
 */
export type Vaccinationsinitiatedratio1 = FieldAnnotations;
/**
 * Annotations for vaccinationsCompletedRatio
 */
export type Vaccinationscompletedratio1 = FieldAnnotations;
/**
 * Ratio of population that are fully vaccinated and have received a booster (or additional) dose.
 */
export type Vaccinationsadditionaldoseratio1 = FieldAnnotations;
/**
 * Date of latest data
 */
export type Lastupdateddate = string;
/**
 * URL linking to Covid Act Now location page.
 */
export type Url1 = string | null;
/**
 * Ratio of people who test positive calculated using a 7-day rolling average.
 */
export type Testpositivityratio2 = number | null;
/**
 * The number of cases per 100k population calculated using a 7-day rolling average.
 */
export type Casedensity2 = number | null;
/**
 * The number of new cases per 100k population over the last week.
 */
export type Weeklynewcasesper100K2 = number | null;
/**
 * Ratio of currently hired tracers to estimated tracers needed based on 7-day daily case average.
 */
export type Contacttracercapacityratio2 = number | null;
/**
 * R_t, or the estimated number of infections arising from a typical case.
 */
export type Infectionrate2 = number | null;
/**
 * 90th percentile confidence interval upper endpoint of the infection rate.
 */
export type Infectionrateci902 = number | null;
/**
 * Ratio of staffed intensive care unit (ICU) beds that are currently in use.
 */
export type Icucapacityratio2 = number | null;
/**
 * Ratio of staffed hospital beds that are currently in use by COVID patients. For counties, this is calculated using HSA-level data for the corresponding area.
 */
export type Bedswithcovidpatientsratio2 = number | null;
/**
 * Number of COVID patients per 100k population admitted in the past week. For counties, this is calculated using HSA-level data for the corresponding area.
 */
export type Weeklycovidadmissionsper100K2 = number | null;
/**
 * Ratio of population that has initiated vaccination.
 */
export type Vaccinationsinitiatedratio2 = number | null;
/**
 * Ratio of population that has completed vaccination.
 */
export type Vaccinationscompletedratio2 = number | null;
/**
 * Ratio of population that are fully vaccinated and have received a booster (or additional) dose.
 */
export type Vaccinationsadditionaldoseratio2 = number | null;
/**
 * Date of timeseries data point
 */
export type Date1 = string;
export type Metricstimeseries = MetricsTimeseriesRow[];
/**
 * Cumulative confirmed or suspected cases.
 */
export type Cases2 = number | null;
/**
 * Cumulative deaths that are suspected or confirmed to have been caused by COVID-19.
 */
export type Deaths2 = number | null;
/**
 * Cumulative positive test results to date
 */
export type Positivetests2 = number | null;
/**
 * Cumulative negative test results to date
 */
export type Negativetests2 = number | null;
/**
 * Number of Contact Tracers
 */
export type Contacttracers2 = number | null;
/**
 *
 * Information about acute bed utilization details.
 *
 * Fields:
 *  * capacity - Current staffed acute bed capacity.
 *  * currentUsageTotal - Total number of acute beds currently in use
 *  * currentUsageCovid - Number of acute beds currently in use by COVID patients.
 *  * weeklyCovidAdmissions - Number of COVID patients admitted in the past week.
 *
 */
export type Hospitalbeds2 = HospitalResourceUtilizationWithAdmissions;
/**
 *
 * Information about acute bed utilization details aggregated for the county's corresponding
 * Health Service Area (HSA). For CBSA, state, and country regions these fields are omitted.
 * For more on HSAs see: https://github.com/covid-projections/covid-data-model/blob/main/data/misc/README.md"
 *
 * Fields:
 *  * capacity - Current staffed acute bed capacity.
 *  * currentUsageTotal - Total number of acute beds currently in use
 *  * currentUsageCovid - Number of acute beds currently in use by COVID patients.
 *  * weeklyCovidAdmissions - Number of COVID patients admitted in the past week.
 *
 */
export type Hsahospitalbeds2 = HospitalResourceUtilizationWithAdmissions;
/**
 *
 * Information about ICU bed utilization details.
 *
 * Fields:
 *  * capacity - Current staffed ICU bed capacity.
 *  * currentUsageTotal - Total number of ICU beds currently in use
 *  * currentUsageCovid - Number of ICU beds currently in use by COVID patients.
 *
 */
export type Icubeds2 = HospitalResourceUtilization;
/**
 *
 * Information about ICU bed utilization details aggregated for the county's corresponding
 * Health Service Area (HSA). For CBSA, state, and country regions these fields are omitted.
 * For For more on HSAs see: https://github.com/covid-projections/covid-data-model/blob/main/data/misc/README.md"
 *
 * Fields:
 *  * capacity - Current staffed ICU bed capacity.
 *  * currentUsageTotal - Total number of ICU beds currently in use
 *  * currentUsageCovid - Number of ICU beds currently in use by COVID patients.
 *
 */
export type Hsaicubeds2 = HospitalResourceUtilization;
/**
 *
 * New confirmed or suspected cases.
 *
 *
 * New cases are a processed timeseries of cases - summing new cases may not equal
 * the cumulative case count.
 *
 * Processing steps:
 *  1. If a region does not report cases for a period of time but then begins reporting again,
 *     we will exclude the first day that reporting recommences. This first day likely includes
 *     multiple days worth of cases and can be misleading to the overall series.
 *  2. We remove any days with negative new cases.
 *  3. We apply an outlier detection filter to the timeseries, which removes any data
 *     points that seem improbable given recent numbers. Many times this is due to
 *     backfill of previously unreported cases.
 *
 */
export type Newcases2 = number | null;
/**
 *
 * New confirmed or suspected COVID-19 deaths.
 *
 * New deaths is an estimate of deaths per day; summing new deaths may not equal the
 * cumulative death count.
 *
 * Processing steps:
 *  1. If a region does not report deaths for a period of time but then begins reporting again,
 *     we will exclude the first day that reporting recommences. This first day likely includes
 *     multiple days worth of deaths and can be misleading to the overall series.
 *  2. We remove any days with negative new deaths.
 *  3. We apply an outlier detection filter to the timeseries, which removes any data
 *     points that seem improbable given recent numbers. Many times this is due to
 *     backfill of previously unreported deaths.
 *
 */
export type Newdeaths2 = number | null;
/**
 * Number of vaccine doses distributed.
 */
export type Vaccinesdistributed2 = number | null;
/**
 *
 * Number of vaccinations initiated.
 *
 * This value may vary by type of vaccine, but for Moderna and Pfizer this indicates
 * number of people vaccinated with the first dose.
 *
 */
export type Vaccinationsinitiated2 = number | null;
/**
 *
 * Number of vaccinations completed.
 *
 * This value may vary by type of vaccine, but for Moderna and Pfizer this indicates
 * number of people vaccinated with both the first and second dose.
 *
 */
export type Vaccinationscompleted2 = number | null;
/**
 * Number of individuals who are fully vaccinated and have received a booster (or additional) dose.
 */
export type Vaccinationsadditionaldose2 = number | null;
/**
 * Total number of vaccine doses administered.
 */
export type Vaccinesadministered2 = number | null;
/**
 * Demographic distributions for administered vaccines.
 */
export type Vaccinesadministereddemographics1 = DemographicDistributions;
/**
 * Demographic distributions for initiated vaccinations.
 */
export type Vaccinationsinitiateddemographics1 = DemographicDistributions;
/**
 * Date of timeseries data point
 */
export type Date2 = string;
export type Actualstimeseries = ActualsTimeseriesRow[];
/**
 * Date of timeseries data point
 */
export type Date3 = string;
export type Risklevelstimeseries = RiskLevelTimeseriesRow[];
/**
 * Date of timeseries data point
 */
export type Date4 = string;
export type Cdctransmissionleveltimeseries = CdcTransmissionLevelTimeseriesRow[];
/**
 * Date of timeseries data point
 */
export type Date5 = string;
export type Communitylevelstimeseries = CommunityLevelsTimeseriesRow[];
/**
 * Timeseries and summary data for multiple regions.
 */
export type AggregateRegionSummaryWithTimeseries = RegionSummaryWithTimeseries[];

/**
 * Summary data for a region with prediction timeseries data and actual timeseries data.
 */
export interface RegionSummaryWithTimeseries {
  fips: Fips;
  country: Country;
  state: State;
  county: County;
  hsa: Hsa;
  hsaName: Hsaname;
  /**
   * Level of region.
   */
  level: AggregationLevel;
  lat: Lat;
  locationId: Locationid;
  long: Long;
  population: Population;
  hsaPopulation: Hsapopulation;
  metrics: Metrics;
  riskLevels: Risklevels;
  /**
   *
   * Community transmission level for region, calculated using the CDC definition.
   *
   * Possible values:
   *     - 0: Low
   *     - 1: Moderate
   *     - 2: Substantial
   *     - 3: High
   *     - 4: Unknown
   *
   * See [definitions of CDC community transmission levels](
   * https://covid.cdc.gov/covid-data-tracker/#cases_community) for more
   * details.
   *
   * Note that the value may differ from what the CDC website reports
   * given we have different data sources. We have also introduced an
   * "Unknown" level for when both case data and test positivity data are
   * missing for at least 15 days. The CDC does not have an "Unknown"
   * level and instead will designate a location as "Low" when case and
   * test positivity data are missing.
   *
   */
  cdcTransmissionLevel: CDCTransmissionLevel;
  communityLevels: CommunityLevels;
  actuals: Actuals;
  annotations: Annotations;
  lastUpdatedDate: Lastupdateddate;
  url: Url1;
  metricsTimeseries: Metricstimeseries;
  actualsTimeseries: Actualstimeseries;
  riskLevelsTimeseries: Risklevelstimeseries;
  cdcTransmissionLevelTimeseries: Cdctransmissionleveltimeseries;
  communityLevelsTimeseries: Communitylevelstimeseries;
}
/**
 * Calculated metrics data based on known actuals.
 */
export interface Metrics {
  testPositivityRatio: Testpositivityratio;
  testPositivityRatioDetails?: TestPositivityRatioDetails | null;
  caseDensity: Casedensity;
  weeklyNewCasesPer100k: Weeklynewcasesper100K;
  contactTracerCapacityRatio: Contacttracercapacityratio;
  infectionRate: Infectionrate;
  infectionRateCI90: Infectionrateci90;
  icuCapacityRatio: Icucapacityratio;
  bedsWithCovidPatientsRatio: Bedswithcovidpatientsratio;
  weeklyCovidAdmissionsPer100k: Weeklycovidadmissionsper100K;
  vaccinationsInitiatedRatio?: Vaccinationsinitiatedratio;
  vaccinationsCompletedRatio?: Vaccinationscompletedratio;
  vaccinationsAdditionalDoseRatio?: Vaccinationsadditionaldoseratio;
}
/**
 * Details about how the test positivity ratio was calculated.
 */
export interface TestPositivityRatioDetails {
  /**
   * Source data for test positivity ratio.
   */
  source: TestPositivityRatioMethod;
}
/**
 * COVID risk levels for a region.
 */
export interface RiskLevels {
  /**
   * Overall risk level for region.
   */
  overall: RiskLevel;
  /**
   * Test positivity ratio risk level.
   */
  testPositivityRatio: RiskLevel;
  /**
   * Case density risk level.
   */
  caseDensity: RiskLevel;
  /**
   * Contact tracer capacity ratio risk level.
   */
  contactTracerCapacityRatio: RiskLevel;
  /**
   * Infection rate risk level.
   */
  infectionRate: RiskLevel;
  /**
   * ICU capacity ratio risk level.
   */
  icuCapacityRatio: RiskLevel;
}
/**
 * Community levels for a region.
 */
export interface CommunityLevels {
  /**
   *
   * CDC Community level for county, as provided by the CDC.
   *
   * Possible values:
   *     - 0: Low
   *     - 1: Medium
   *     - 2: High
   *
   * See https://www.cdc.gov/coronavirus/2019-ncov/science/community-levels.html
   * for details about how the Community Level is calculated and should be
   * interpretted.
   *
   * Note that we provide two versions of the Community Level. One is called
   * canCommunityLevel which is calculated on a daily basis using CAN's data
   * sources and is available for states, counties, and metros.  The other is
   * called cdcCommunityLevel and is the raw Community Level published by the
   * CDC. It is only available for counties, and updates on a weekly basis.
   *
   */
  cdcCommunityLevel: CommunityLevel;
  /**
   *
   * Community level for region, calculated using the CDC definition but with CAN
   * data sources.
   *
   * Possible values:
   *     - 0: Low
   *     - 1: Medium
   *     - 2: High
   *
   * See https://www.cdc.gov/coronavirus/2019-ncov/science/community-levels.html
   * for details about how the Community Level is calculated and should be
   * interpretted.
   *
   * Note that we provide two versions of the Community Level. One is called
   * canCommunityLevel which is calculated on a daily basis using CAN's data
   * sources and is available for states, counties, and metros.  The other is
   * called cdcCommunityLevel and is the raw Community Level published by the
   * CDC. It is only available for counties, and updates on a weekly basis.
   *
   */
  canCommunityLevel: CommunityLevel;
}
/**
 * Known actuals data.
 */
export interface Actuals {
  cases: Cases;
  deaths: Deaths;
  positiveTests: Positivetests;
  negativeTests: Negativetests;
  contactTracers: Contacttracers;
  hospitalBeds: Hospitalbeds;
  hsaHospitalBeds: Hsahospitalbeds;
  icuBeds: Icubeds;
  hsaIcuBeds: Hsaicubeds;
  newCases: Newcases;
  newDeaths: Newdeaths;
  vaccinesDistributed?: Vaccinesdistributed;
  vaccinationsInitiated?: Vaccinationsinitiated;
  vaccinationsCompleted?: Vaccinationscompleted;
  vaccinationsAdditionalDose?: Vaccinationsadditionaldose;
  vaccinesAdministered?: Vaccinesadministered;
  vaccinesAdministeredDemographics?: Vaccinesadministereddemographics;
  vaccinationsInitiatedDemographics?: Vaccinationsinitiateddemographics;
}
/**
 * Base model for API output.
 */
export interface HospitalResourceUtilizationWithAdmissions {
  capacity: Capacity;
  currentUsageTotal: Currentusagetotal;
  currentUsageCovid: Currentusagecovid;
  weeklyCovidAdmissions: Weeklycovidadmissions;
}
/**
 * Base model for API output.
 */
export interface HospitalResourceUtilization {
  capacity: Capacity1;
  currentUsageTotal: Currentusagetotal1;
  currentUsageCovid: Currentusagecovid1;
}
/**
 * Distributions of demographic data.
 *
 * Note that different regions may have different demographic distributions for
 * the same field.  For instance, health departments in different states may report
 * different age ranges.
 *
 * The data provided matches the source distributions.
 */
export interface DemographicDistributions {
  age?: Age;
  race?: Race;
  ethnicity?: Ethnicity;
  sex?: Sex;
}
/**
 * Annotations for each field.
 */
export interface Annotations {
  cases?: Cases1;
  deaths?: Deaths1;
  positiveTests?: Positivetests1;
  negativeTests?: Negativetests1;
  contactTracers?: Contacttracers1;
  hospitalBeds?: Hospitalbeds1;
  hsaHospitalBeds?: Hsahospitalbeds1;
  icuBeds?: Icubeds1;
  hsaIcuBeds?: Hsaicubeds1;
  newCases?: Newcases1;
  newDeaths?: Newdeaths1;
  vaccinesDistributed?: Vaccinesdistributed1;
  vaccinationsInitiated?: Vaccinationsinitiated1;
  vaccinationsCompleted?: Vaccinationscompleted1;
  vaccinationsAdditionalDose?: Vaccinationsadditionaldose1;
  vaccinesAdministered?: Vaccinesadministered1;
  testPositivityRatio?: Testpositivityratio1;
  caseDensity?: Casedensity1;
  weeklyNewCasesPer100k?: Weeklynewcasesper100K1;
  contactTracerCapacityRatio?: Contacttracercapacityratio1;
  infectionRate?: Infectionrate1;
  infectionRateCI90?: Infectionrateci901;
  icuCapacityRatio?: Icucapacityratio1;
  bedsWithCovidPatientsRatio?: Bedswithcovidpatientsratio1;
  weeklyCovidAdmissionsPer100k?: Weeklycovidadmissionsper100K1;
  vaccinationsInitiatedRatio?: Vaccinationsinitiatedratio1;
  vaccinationsCompletedRatio?: Vaccinationscompletedratio1;
  vaccinationsAdditionalDoseRatio?: Vaccinationsadditionaldoseratio1;
}
/**
 * Annotations associated with one field.
 */
export interface FieldAnnotations {
  sources: Sources;
  anomalies: Anomalies;
}
/**
 * Base model for API output.
 */
export interface FieldSource {
  /**
   * The type of data source from a CAN list of data source types
   */
  type?: FieldSourceType;
  url?: Url;
  name?: Name;
}
/**
 * Base model for API output.
 */
export interface AnomalyAnnotation {
  date: Date;
  /**
   * Type of annotation
   */
  type: TagType;
  original_observation: OriginalObservation;
}
/**
 * Metrics data for a specific day.
 */
export interface MetricsTimeseriesRow {
  testPositivityRatio: Testpositivityratio2;
  testPositivityRatioDetails?: TestPositivityRatioDetails | null;
  caseDensity: Casedensity2;
  weeklyNewCasesPer100k: Weeklynewcasesper100K2;
  contactTracerCapacityRatio: Contacttracercapacityratio2;
  infectionRate: Infectionrate2;
  infectionRateCI90: Infectionrateci902;
  icuCapacityRatio: Icucapacityratio2;
  bedsWithCovidPatientsRatio: Bedswithcovidpatientsratio2;
  weeklyCovidAdmissionsPer100k: Weeklycovidadmissionsper100K2;
  vaccinationsInitiatedRatio?: Vaccinationsinitiatedratio2;
  vaccinationsCompletedRatio?: Vaccinationscompletedratio2;
  vaccinationsAdditionalDoseRatio?: Vaccinationsadditionaldoseratio2;
  date: Date1;
}
/**
 * Actual data for a specific day.
 */
export interface ActualsTimeseriesRow {
  cases: Cases2;
  deaths: Deaths2;
  positiveTests: Positivetests2;
  negativeTests: Negativetests2;
  contactTracers: Contacttracers2;
  hospitalBeds: Hospitalbeds2;
  hsaHospitalBeds: Hsahospitalbeds2;
  icuBeds: Icubeds2;
  hsaIcuBeds: Hsaicubeds2;
  newCases: Newcases2;
  newDeaths: Newdeaths2;
  vaccinesDistributed?: Vaccinesdistributed2;
  vaccinationsInitiated?: Vaccinationsinitiated2;
  vaccinationsCompleted?: Vaccinationscompleted2;
  vaccinationsAdditionalDose?: Vaccinationsadditionaldose2;
  vaccinesAdministered?: Vaccinesadministered2;
  vaccinesAdministeredDemographics?: Vaccinesadministereddemographics1;
  vaccinationsInitiatedDemographics?: Vaccinationsinitiateddemographics1;
  date: Date2;
}
/**
 * Timeseries data for risk levels. Currently only surfacing overall risk level for region.
 */
export interface RiskLevelTimeseriesRow {
  /**
   * Overall risk level for region .
   */
  overall: RiskLevel;
  /**
   * Case density risk level for region.
   */
  caseDensity: RiskLevel;
  date: Date3;
}
/**
 * Base model for API output.
 */
export interface CdcTransmissionLevelTimeseriesRow {
  date: Date4;
  /**
   *
   * Community transmission level for region, calculated using the CDC definition.
   *
   * Possible values:
   *     - 0: Low
   *     - 1: Moderate
   *     - 2: Substantial
   *     - 3: High
   *     - 4: Unknown
   *
   * See [definitions of CDC community transmission levels](
   * https://covid.cdc.gov/covid-data-tracker/#cases_community) for more
   * details.
   *
   * Note that the value may differ from what the CDC website reports
   * given we have different data sources. We have also introduced an
   * "Unknown" level for when both case data and test positivity data are
   * missing for at least 15 days. The CDC does not have an "Unknown"
   * level and instead will designate a location as "Low" when case and
   * test positivity data are missing.
   *
   */
  cdcTransmissionLevel: CDCTransmissionLevel;
}
/**
 * Timeseries data for community levels.
 */
export interface CommunityLevelsTimeseriesRow {
  /**
   *
   * CDC Community level for county, as provided by the CDC.
   *
   * Possible values:
   *     - 0: Low
   *     - 1: Medium
   *     - 2: High
   *
   * See https://www.cdc.gov/coronavirus/2019-ncov/science/community-levels.html
   * for details about how the Community Level is calculated and should be
   * interpretted.
   *
   * Note that we provide two versions of the Community Level. One is called
   * canCommunityLevel which is calculated on a daily basis using CAN's data
   * sources and is available for states, counties, and metros.  The other is
   * called cdcCommunityLevel and is the raw Community Level published by the
   * CDC. It is only available for counties, and updates on a weekly basis.
   *
   */
  cdcCommunityLevel: CommunityLevel;
  /**
   *
   * Community level for region, calculated using the CDC definition but with CAN
   * data sources.
   *
   * Possible values:
   *     - 0: Low
   *     - 1: Medium
   *     - 2: High
   *
   * See https://www.cdc.gov/coronavirus/2019-ncov/science/community-levels.html
   * for details about how the Community Level is calculated and should be
   * interpretted.
   *
   * Note that we provide two versions of the Community Level. One is called
   * canCommunityLevel which is calculated on a daily basis using CAN's data
   * sources and is available for states, counties, and metros.  The other is
   * called cdcCommunityLevel and is the raw Community Level published by the
   * CDC. It is only available for counties, and updates on a weekly basis.
   *
   */
  canCommunityLevel: CommunityLevel;
  date: Date5;
}
