/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Run 'yarn update-api-types' to regenerate.
 */

export type Date = string;
/**
 * Number of hospital beds projected to be in-use or that were actually in use (if in the past)
 */
export type Hospitalbedsrequired = number;
/**
 * Number of hospital beds projected to be in-use or actually in use (if in the past)
 */
export type Hospitalbedcapacity = number;
/**
 * Number of ICU beds projected to be in-use or that were actually in use (if in the past)
 */
export type Icubedsinuse = number;
/**
 * Number of ICU beds projected to be in-use or actually in use (if in the past)
 */
export type Icubedcapacity = number;
/**
 * Number of cumulative deaths
 */
export type Cumulativedeaths = number;
/**
 * Number of cumulative infections
 */
export type Cumulativeinfected = number;

export interface CANPredictionTimeseriesRow {
  date: Date;
  hospitalBedsRequired: Hospitalbedsrequired;
  hospitalBedCapacity: Hospitalbedcapacity;
  ICUBedsInUse: Icubedsinuse;
  ICUBedCapacity: Icubedcapacity;
  cumulativeDeaths: Cumulativedeaths;
  cumulativeInfected: Cumulativeinfected;
}
