/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Run 'yarn update-api-types' to regenerate.
 */

/**
 * The state name
 */
export type Statename = string;
/**
 * The county name
 */
export type Countyname = string;
/**
 * Fips for State + County. Five character code
 */
export type Fips = string;
/**
 * Date of latest data
 */
export type Lastupdateddate = string;
/**
 * Shortfall of beds needed at the peek hospitalizaitons
 */
export type Peakshortfall = number;
/**
 * Date of peak hospitalizations
 */
export type Peakdate = string;
/**
 * Date when hospitals overload
 */
export type Shortagestartdate = string;
export type Data = CANPredictionAPIRow[];

export interface CANPredictionAPI {
  data: Data;
}
export interface CANPredictionAPIRow {
  stateName: Statename;
  countyName: Countyname;
  fips: Fips;
  lastUpdatedDate: Lastupdateddate;
  projections: _Projections;
}
export interface _Projections {
  hospitalBeds: _HospitalBeds;
}
export interface _HospitalBeds {
  peakShortfall: Peakshortfall;
  peakDate: Peakdate;
  shortageStartDate: Shortagestartdate;
}
