/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Run 'yarn update-api-types' to regenerate.
 */

export type Countryname = string;
/**
 * Fips for State + County. Five character code
 */
export type Fips = string;
/**
 * Lattitude of point within the state or county
 */
export type Lat = number;
/**
 * Longitude of point within the state or county
 */
export type Long = number;
/**
 * Date of latest data
 */
export type Lastupdateddate = string;
/**
 * Projection about total hospital bed utilization
 */
export type Totalhospitalbeds = _ResourceUsageProjection;
/**
 * Shortfall of resource needed at the peek utilization
 */
export type Peakshortfall = number;
/**
 * Date of peak resource utilization
 */
export type Peakdate = string;
/**
 * Date when resource shortage begins
 */
export type Shortagestartdate = string;
/**
 * Projection about ICU hospital bed utilization
 */
export type Icubeds = _ResourceUsageProjection;
/**
 * Cumulative number of deaths within projection window
 */
export type Cumulativedeaths = number;
/**
 * Peak number of deaths within projection window
 */
export type Peakdeaths = number;
/**
 * Date of peak number of deaths
 */
export type Peakdeathsdate = string;
/**
 * Date the projection goes until
 */
export type Enddate = string;
/**
 * Total population in geographic area
 */
export type Population = number;
/**
 * Name of high-level intervention in-place
 */
export type Intervention = string;
/**
 * Number of confirmed cases so far
 */
export type Cumulativeconfirmedcases = number;
/**
 * Number of deaths so far
 */
export type Cumulativedeaths1 = number;
/**
 * Total capacity for resource
 */
export type Capacity = number;
/**
 * Currently used capacity for resource
 */
export type Currentusage = number;
/**
 * Number of contact tracers in the region
 */
export type ContactTracersCount = number;
export type Data = CovidActNowAreaSummary[];

export interface CovidActNowStatesAPI {
  data: Data;
}
export interface CovidActNowAreaSummary {
  countryName?: Countryname;
  fips: Fips;
  lat: Lat;
  long: Long;
  lastUpdatedDate: Lastupdateddate;
  projections: _Projections;
  actuals: _Actuals;
}
export interface _Projections {
  totalHospitalBeds: Totalhospitalbeds;
  ICUBeds: Icubeds;
  cumulativeDeaths: Cumulativedeaths;
  peakDeaths: Peakdeaths;
  peakDeathsDate: Peakdeathsdate;
  endDate: Enddate;
}
export interface _ResourceUsageProjection {
  peakShortfall: Peakshortfall;
  peakDate: Peakdate;
  shortageStartDate: Shortagestartdate;
}
export interface _Actuals {
  population: Population;
  intervention: Intervention;
  cumulativeConfirmedCases: Cumulativeconfirmedcases;
  cumulativeDeaths: Cumulativedeaths1;
  hospitalBeds: _ResourceUtilization;
  ICUBeds: _ResourceUtilization;
  contactTracersCount?: ContactTracersCount;
}
export interface _ResourceUtilization {
  capacity: Capacity;
  currentUsage: Currentusage;
}
