/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Run 'yarn update-api-types' to regenerate.
 */

/**
 * Total capacity for resource.
 */
export type Capacity = number;
/**
 * Currently used capacity for resource by all patients (COVID + Non-COVID)
 */
export type Currentusagetotal = number;
/**
 * Currently used capacity for resource by COVID
 */
export type Currentusagecovid = number;
/**
 * Typical used capacity rate for resource. This excludes any COVID usage.
 */
export type Typicalusagerate = number;

/**
 * Base model for API output.
 */
export interface HospitalResourceUtilization {
  capacity?: Capacity;
  currentUsageTotal?: Currentusagetotal;
  currentUsageCovid?: Currentusagecovid;
  typicalUsageRate?: Typicalusagerate;
}
