/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Run 'yarn update-api-types' to regenerate.
 */

/**
 * Ratio of people who test positive calculated using a 7 day rolling average.
 */
export type Testpositivity = number;
/**
 * The number of cases per 100k population calculated using a 7 day rolling average.
 */
export type Casedensity = number;
export type Date = string;

/**
 * Calculated metrics data based on known actuals.
 */
export interface MetricsTimeseriesRow {
  testPositivity: Testpositivity;
  caseDensity: Casedensity;
  date: Date;
}
