# This file controls the configuration of our Netlify CMS UI+content structure
# 'branch' is the branch where all copy changes made in the CMS UI will be committed
# Netlify CMS docs: https://www.netlifycms.org/docs/intro/
backend:
  name: github
  repo: covid-projections/covid-projections
  branch: cms-content-entry
  base_url: https://api.netlify.com

media_folder: 'public/images_cms'
public_folder: '/images_cms'

collections:
  - name: 'about'
    label: 'About'
    format: 'json'
    description: 'About page content'
    slug: '{{slug}}'
    editor:
      preview: true
    files:
      - name: 'About'
        label: 'About page content'
        file: 'src/cms-content/about/about-page.json'
        fields:
          - { label: 'Page Header', name: 'pageHeader', widget: 'string' }
          - { label: 'Intro: Header', name: 'introHeader', widget: 'string' }
          - {
              label: 'Intro: Content',
              name: 'introContent',
              widget: 'markdown',
            }
          - {
              label: 'Partners: Header',
              name: 'partnersHeader',
              widget: 'string',
            }
          - label: 'Partners: Content'
            name: 'partnersContent'
            widget: 'list'
            fields:
              - { label: 'Section copy', name: 'copy', widget: 'markdown' }
              - label: 'Logos'
                name: 'logos'
                widget: 'list'
                fields:
                  - { label: 'Alt text', name: 'altText', widget: 'string' }
                  - { label: 'Image', name: 'image', widget: 'image' }
                  - { label: 'Url', name: 'url', widget: 'string' }
  - name: donate
    label: Donate
    format: json
    description: Donate page content
    slug: '{{slug}}'
    editor:
      preview: true
    files:
      - name: Donate
        label: Donate page content
        file: src/cms-content/donate/donate-page.json
        fields:
          - label: Header Lines
            name: headerLines
            widget: list
          - label: Intro
            name: intro
            widget: markdown
          - label: Sections
            name: sections
            widget: list
            fields:
              - label: Section Title
                name: title
                widget: string
              - label: Section Copy
                name: copy
                widget: markdown
  - name: recommendations
    label: Recommendations
    format: json
    description: Recommendations content
    slug: '{{slug}}'
    editor:
      preview: true
    files:
      - name: Recommendations-Main
        label: 'Main'
        file: src/cms-content/recommendations/recommendations-main.json
        fields:
          - label: Header
            name: header
            widget: string
            default: true
          - label: Recommendations
            name: recommendations
            widget: list
            fields:
              - { label: Body, name: body, widget: markdown }
              - { label: Source, name: source, widget: string }
              - { label: Category, name: category, widget: string }
              - { label: Level, name: level, widget: string }
              - { label: ID, name: id, widget: string }
          - label: Footer
            name: footer
            widget: object
            collapsed: true
            fields:
              - {
                  label: Modal button label,
                  name: modalButtonLabel,
                  widget: string,
                }
              - {
                  label: Feedback button label,
                  name: feedbackButtonLabel,
                  widget: string,
                }
              - { label: Share text, name: shareText, widget: markdown }
          - label: Icons
            name: icons
            widget: list
            fields:
              - { label: Category, name: category, widget: string }
              - { label: Alt text, name: altText, widget: string }
              - { label: Icon image, name: iconImage, widget: image }
      - name: Recommendations-Modal
        label: 'Modal'
        file: src/cms-content/recommendations/recommendations-modal.json
        fields:
          - { label: 'Header', name: 'header', widget: 'string', default: true }
          - label: Section - Federal Task Force
            name: federalTaskForce
            widget: object
            collapsed: true
            fields:
              - { label: Source Name, name: sourceName, widget: string }
              - { label: Description, name: description, widget: markdown }
              - label: Levels
                name: levels
                widget: list
                fields:
                  - { label: Color, name: color, widget: string }
                  - { label: Content, name: content, widget: markdown }
          - label: Section - Harvard
            name: harvard
            widget: object
            collapsed: true
            fields:
              - { label: Source Name, name: sourceName, widget: string }
              - { label: Description, name: description, widget: markdown }
              - label: Levels
                name: levels
                widget: list
                fields:
                  - { label: Color, name: color, widget: string }
                  - { label: Content, name: content, widget: markdown }
  - name: learn
    label: Learn
    format: json
    description: Learn content
    slug: '{{slug}}'
    editor:
      preview: true
    files:
      - name: Learn-Landing
        label: 'Landing page'
        file: src/cms-content/learn/learn-landing.json
        fields:
          - label: Header
            name: header
            widget: string
            default: true
          - label: Intro
            name: intro
            widget: markdown
            default: true
          - label: Sections
            name: sections
            widget: list
            fields:
              - { label: Section title, name: sectionTitle, widget: string }
              - { label: Section ID, name: sectionId, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: Button CTA, name: buttonCta, widget: string }
              - { label: Button redirect, name: buttonRedirect, widget: text }
          - label: Metadata title
            name: metadataTitle
            widget: text
            default: true
          - label: Metadata description
            name: metadataDescription
            widget: text
            default: true
      - name: Learn-Glossary
        label: 'Glossary'
        file: src/cms-content/learn/learn-glossary.json
        fields:
          - label: Header
            name: header
            widget: string
            default: true
          - label: Intro
            name: intro
            widget: markdown
            default: true
          - label: Terms
            name: terms
            widget: list
            fields:
              - { label: Term, name: term, widget: string }
              - { label: Term ID, name: termId, widget: string }
              - { label: Definition, name: definition, widget: markdown }
          - label: Metadata title
            name: metadataTitle
            widget: text
            default: true
          - label: Metadata description
            name: metadataDescription
            widget: text
            default: true
      - name: Learn-Faq
        label: 'FAQ'
        file: src/cms-content/learn/learn-faq.json
        fields:
          - label: Header
            name: header
            widget: string
            default: true
          - label: Intro
            name: intro
            widget: markdown
            default: true
          - label: Sections
            name: sections
            widget: list
            fields:
              - { label: Section title, name: sectionTitle, widget: string }
              - { label: Section ID, name: sectionId, widget: string }
              - label: Questions
                name: questions
                widget: list
                fields:
                  - { label: Question, name: question, widget: text }
                  - { label: Answer, name: answer, widget: markdown }
          - label: Metadata title
            name: metadataTitle
            widget: text
            default: true
          - label: Metadata description
            name: metadataDescription
            widget: text
            default: true
      - name: Footer
        label: 'Footer'
        file: src/cms-content/learn/footer.json
        fields:
          - { label: Body, name: body, widget: markdown, default: true }
      - name: Case Studies
        file: 'src/cms-content/learn/case-studies.json'
        label: Case Studies
        fields:
          - label: Header
            name: header
            widget: text
            hint: Header for the case studies landing page
          - label: Intro
            name: intro
            widget: markdown
            hint: Introduction for the case studies landing page
          - label: Categories
            name: categories
            widget: list
            fields:
              - {
                  label: Category Name,
                  name: header,
                  widget: text,
                  hint: Name of the category,
                }
              - {
                  label: Category ID,
                  name: categoryId,
                  widget: string,
                  hint: 'All lowercase, divided by dashes if multi-word (ex: public-health)',
                }
              - label: Case Studies
                name: caseStudies
                hint: Case studies for the category
                widget: list
                fields:
                  - {
                      label: Header,
                      name: header,
                      widget: text,
                      hint: Title for the case study page,
                    }
                  - {
                      label: Short Title,
                      name: shortTitle,
                      widget: text,
                      hint: Short title for the case studies landing page,
                    }
                  - {
                      label: Author,
                      name: author,
                      minimal: true,
                      widget: markdown,
                      hint: 'Name of the author of the case study',
                    }
                  - {
                      label: Case Study ID,
                      name: caseStudyId,
                      widget: string,
                      hint: 'Added to the URL, formatted with no spaces, separated by dashes (ex: ibm-melanie-curry)',
                    }
                  - {
                      label: Logo,
                      name: logoUrl,
                      widget: image,
                      hint: Logo for the case studies page (400x280),
                      allow_multiple: false,
                    }
                  - {
                      label: Logo Alt Text,
                      name: logoAltText,
                      widget: string,
                      hint: Alt-text for the logo,
                    }
                  - {
                      label: Summary,
                      name: summary,
                      widget: markdown,
                      hint: Summary to show on the case studies landing page,
                    }
                  - {
                      label: Body,
                      name: body,
                      widget: markdown,
                      hint: Full content of the case study,
                    }
                  - {
                      label: Tags,
                      name: tags,
                      widget: list,
                      hint: 'Optional tags for the case study. Separate with commas. (ex: api, embed, etc)',
                    }
