/**
 * Run via: yarn update-api-types
 *
 * Reads schema files from
 * https://github.com/covid-projections/covid-data-model/tree/main/api/schemas
 * and generates corresponding typescript definition files in src/models/api/
 */

import yargs from 'yargs';
import fetch from 'node-fetch';
import { compile } from 'json-schema-to-typescript';
import fs from 'fs-extra';
import path from 'path';

const SCHEMA_FILES = [
  'Actuals.json',
  'ActualsTimeseriesRow.json',
  'AggregateFlattenedTimeseries.json',
  'AggregateRegionSummary.json',
  'AggregateRegionSummaryWithTimeseries.json',
  'Metrics.json',
  'MetricsTimeseriesRow.json',
  'RegionSummary.json',
  'RegionSummaryWithTimeseries.json',
  'HospitalResourceUtilization.json',
];

const BANNER_COMMENT = `
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Run 'yarn update-api-types' to regenerate.
 */
`;

const OUTPUT_FOLDER = path.join(__dirname, '..', 'src', 'api', 'schema');
const schemasBaseUrl = (branch: string) =>
  `https://github.com/covid-projections/covid-data-model/raw/${branch}/api/schemas_v2/`;

const main = async (branch: string) => {
  for (const file of SCHEMA_FILES) {
    const response = await fetch(schemasBaseUrl(branch) + file, {});
    const json = await response.json();
    forceAdditionalPropertiesFalse(json);
    const ts = await compile(json, file.replace('.json', ''), {
      bannerComment: BANNER_COMMENT,
    });
    const outFile = path.join(OUTPUT_FOLDER, file.replace('.json', '.d.ts'));
    await fs.writeFile(outFile, ts);
    console.log(`Generated ${outFile}`);
  }
};

// HACK: We modify the schema to disable 'additionalProperties' on all types so
// that the generated TypeScript definitions are more restrictive and doesn't
// let us accidentally access nonexistent properties.
function forceAdditionalPropertiesFalse(jsonSchema: any) {
  jsonSchema['additionalProperties'] = false;
  const definitions = jsonSchema['definitions'] || {};
  for (const type in definitions) {
    definitions[type]['additionalProperties'] = false;
  }
}

if (require.main === module) {
  const argv = yargs.options({
    branch: {
      default: 'main',
      description: 'covid-data-model branch to pull api schemas from.',
    },
  }).argv;

  main(argv.branch)
    .then(() => {
      console.log('Done.');
      process.exit(0);
    })
    .catch(err => {
      console.error('Error', err);
      process.exit(-1);
    });
}
