# Publish to Chromatic
#
# https://www.chromatic.com/docs/github-actions
name: 'Chromatic'
on:
  push:
    # Workflows triggered by Dependabot don't have access to secrets, which
    # will cause this workflow to fail. See
    # https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
    branches-ignore:
      - 'dependabot/**'
      - 'bump-snapshot-**'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          # https://github.com/act-now-coalition/covid-act-now-website/settings/secrets/actions
          token: ${{ secrets.CAN_ROBOT_PERSONAL_ACCESS_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
