name: Send Vaccination Alerts

# TODO: Change to scheduled once we are confident
on:
  workflow_dispatch:
    inputs:
      firebase_env:
        description: 'Environment to run against (prod, dev, or staging)'
        required: true
        default: prod
      dry_run:
        description: 'Whether to only do a safe dry run (true) or actually send the emails (false)'
        required: true
        default: true

env:
  FIREBASE_ENV: ${{ github.event.inputs.firebase_env }}
  DRY_RUN: ${{ github.event.inputs.dry_run }}

jobs:
  send-vaccination-alerts:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
        with:
          repository: covid-projections/covid-projections
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install

      # Write appropriate service account file for FIREBASE_ENV.
      - name: Write Dev Service Account
        if: ${{ env.FIREBASE_ENV == 'dev' }}
        run: echo "$SERVICE_ACCOUNT" > scripts/common/firebase/google-service-account.json
        env:
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}
      - name: Write Staging Service Account
        if: ${{ env.FIREBASE_ENV == 'staging' }}
        run: echo "$SERVICE_ACCOUNT" > scripts/common/firebase/google-service-account.json
        env:
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}
      - name: Write Prod Service Account
        if: ${{ env.FIREBASE_ENV == 'prod' }}
        run: echo "$SERVICE_ACCOUNT" > scripts/common/firebase/google-service-account.json
        env:
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}

      - name: Generate the vaccination info update
        run: yarn vaccinations-generate-alerts

      - name: Generate the list of users and locations to email
        run: yarn vaccinations-generate-users-to-email

      - name: Send vaccination alert emails (dry run)
        if: ${{ env.DRY_RUN  == 'true' }}
        run: yarn vaccinations-send-alert-emails --dryRun
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Send vaccination alert emails
        if: ${{ env.DRY_RUN == 'false' }}
        run: yarn vaccinations-send-alert-emails
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Slack notifications
      - name: Slack notification
        if: ${{ env.FIREBASE_ENV == 'prod' && job.status != 'success' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          STATUS: ${{job.status}}
        uses: Ilshidur/action-slack@fb92a78a305a399cd6d8ede99d641f2b9224daf3
        with:
          args: '[${{env.FIREBASE_ENV}}] vaccination-alerts failed: {{STATUS}}'
      - name: Slack notification
        if: ${{ env.FIREBASE_ENV == 'prod' && job.status == 'success'}}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          STATUS: ${{job.status}}
        uses: Ilshidur/action-slack@fb92a78a305a399cd6d8ede99d641f2b9224daf3
        with:
          args: '[${{env.FIREBASE_ENV}}] Successfully sent vaccination alerts'
